/* Engelsk oversettelse av all tekst på siden.
   Nøkkel = norsk tekst nøyaktig slik den står på siden, verdi = engelsk.
   Endrer du en norsk tekst i index.html eller js/, må nøkkelen her endres likt.
   Tekst som ikke finnes her, blir stående på norsk i engelsk visning. */
const I18N_EN = {
 "Interaktiv presentasjon": "Interactive presentation",
 "Her viser vi hvordan Dalux fungerer, med konkrete eksempler fra et byggeprosjekt.": "This shows how Dalux works, with concrete examples from a construction project.",
 "Dette er": "This is",
 "ikke": "not",
 "en ferdig oppskrift. En prosjektadministrator setter opp hvert prosjekt etter behov.": "a finished recipe. A project administrator sets up each project to fit its needs.",
 "Velg modul": "Choose a module",
 "Oppgaver, sjekklister og arbeidsflyt": "Tasks, checklists and workflows",
 "Filer, kommentarer og ISO 19650": "Files, comments and ISO 19650",
 "Felles begreper": "Shared concepts",
 "Brukergrupper": "User groups",
 "← Moduler": "← Modules",
 "⛶ Fullskjerm": "⛶ Full screen",
 "✕ Avslutt fullskjerm": "✕ Exit full screen",
 "Entrepriser": "Work packages",
 "Oppgaver": "Tasks",
 "Fra liste til virkelighet": "From list to reality",
 "Klikk på fanene for å bytte visning, og på en entreprise for å se arbeidsforløpene": "Click the tabs to switch views, and click a work package to see its workflows",
 "Listevisning": "List view",
 "Kommunikasjonsflyt": "Communication channel",
 "+ Legg til entreprise": "+ Add work package",
 "👥 Vis detaljer": "👥 Show details",
 "🖨 Skriv ut": "🖨 Print",
 "+ Tilføy filter": "+ Add filter",
 "🔍 Søk": "🔍 Search",
 "Oppretter": "Creator",
 "Svarer": "Responder",
 "Rolle": "Role",
 "Totalentreprenør / Systemeier": "Main contractor / System owner",
 "Klikk på en entreprise for å se arbeidsforløpene": "Click a work package to see its workflows",
 "Klikk på en entreprise for å se arbeidsforløpene. All kommunikasjon går via systemeier": "Click a work package to see its workflows. All communication goes through the system owner",
 "Lukk arbeidsforløp": "Close workflows",
 "Slik kan arbeidsforløpene se ut i entreprisen": "This is how the workflows in the work package can look",
 "Lite prosjekt": "Small project",
 "Stort prosjekt": "Large project",
 "Fag": "Trade",
 "Oppgaveforløp": "Task workflow",
 "TE": "MC",
 "Rapport": "Report",
 "Utbedring": "Fix",
 "HMS-ledere": "Safety managers",
 "HMS-forløp": "Safety workflow",
 "Kvalitetsforløp": "Quality workflow",
 "Kvalitetsleder": "Quality manager",
 "HMS-leder": "Safety manager",
 "Miljøforløp": "Environment workflow",
 "Ytre miljø": "Environment",
 "Kontroll →": "Check →",
 "← Utbedres": "← To be fixed",
 "I små prosjekter behandler totalentreprenøren alle saker, ofte fordi samme person har flere \"hatter\".": "In small projects the main contractor handles every case, often because the same person wears several \"hats\".",
 "I små prosjekter behandler totalentreprenøren alle saker, ofte fordi samme person har flere \"hatter\". HMS-observasjoner kan alle på prosjektet opprette, de sendes til HMS-lederne utenfor arbeidsforløpene, og kommer tilbake som en HMS-oppgave for utbedring.": "In small projects the main contractor handles every case, often because the same person wears several \"hats\". Anyone on the project can create safety observations. They go to the safety managers outside the workflows and come back as a safety issue to be fixed.",
 "I større prosjekter splittes arbeidet på dedikerte fagledere. Slik unngår du at folk får varsler om saker som ikke er deres ansvar. HMS-observasjoner kan alle på prosjektet opprette, de sendes til HMS-lederne utenfor arbeidsforløpene, og kommer tilbake som en HMS-oppgave for utbedring.": "In larger projects the work is split between dedicated trade leads. That way people are not notified about cases they are not responsible for. Anyone on the project can create safety observations. They go to the safety managers outside the workflows and come back as a safety issue to be fixed.",
 "Ny →": "New →",
 "Internentreprise": "In-house works",
 "Internentr.": "In-house",
 "[Byggherre] Utvikling av byggeprosjekter": "[Client] Development of building projects",
 "Byggherre": "Client",
 "Riving av bygninger og andre konstruksjoner": "Demolition of buildings and other structures",
 "Riving": "Demolition",
 "Grunnarbeid": "Groundworks",
 "Prøveboring": "Test drilling",
 "Elektrisk installasjonsarbeid": "Electrical installation",
 "Elektriker": "Electrician",
 "Rørleggerarbeid": "Plumbing",
 "Rørlegger": "Plumber",
 "Ventilasjonsarbeid": "Ventilation work",
 "Ventilasjon": "Ventilation",
 "Stukkatørarbeid og pussing": "Plastering and rendering",
 "Stukkatør": "Plasterer",
 "Gulvlegging og tapetsering": "Flooring and wallpapering",
 "Gulv/Tapet": "Floors/Walls",
 "Malerarbeid": "Painting",
 "Maler": "Painter",
 "Glassarbeid": "Glazing",
 "Glass": "Glazier",
 "Blikkenslagerarbeid": "Sheet metal work",
 "Blikkenslager": "Sheet metal",
 "Takarbeid": "Roofing",
 "Tak": "Roofer",
 "Betongelementmontasje": "Precast concrete assembly",
 "Betongelement": "Precast",
 "Betong og støpearbeid": "Concrete and casting",
 "Betong/Støp": "Concrete",
 "Tømrerarbeid": "Carpentry",
 "Tømrer": "Carpenter",
 "Murerarbeid": "Masonry",
 "Murer": "Mason",
 "Oppgaver: Fra opprettet til lukket": "Tasks: from created to closed",
 "Følg en oppgave gjennom arbeidsforløpet, fra oppretting til godkjenning.": "Follow a task through the workflow, from creation to approval.",
 "Enkel oppgave": "Simple task",
 "Løses i ett forløp": "Resolved in one workflow",
 "Kryssforløp": "Cross-workflow",
 "Sendes til annet forløp": "Sent on to another workflow",
 "Observasjon til HMS-oppgave": "Observation to safety issue",
 "Godkjenning": "Approval",
 "Endringsmelding med ledd": "Change notice with stages",
 "Beskrivelse": "Description",
 "Forløp 1": "Workflow 1",
 "Forløp 2": "Workflow 2",
 "Forløp": "Workflow",
 "Varsel om endring": "Change notification",
 "UE": "SC",
 "Innmelder": "Reporter",
 "Behandler": "Handler",
 "Godkjenner": "Approver",
 "Omtvistet": "Disputed",
 "Lukket med uenighet": "Closed with disagreement",
 "← Forrige": "← Previous",
 "Neste →": "Next →",
 "Neste steg →": "Next step →",
 "↑ Til toppen": "↑ Back to top",
 "⟳ Start på nytt": "⟳ Start again",
 "Tildeler": "Assigner",
 "Kontrollør": "Checker",
 "Fagarbeider": "Tradesperson",
 "Melder": "Reports",
 "Mottaker": "Recipient",
 "HMS-observasjon": "Safety observation",
 "Utfører": "Performs",
 "Beslutter": "Decides",
 "Ledd 1 · Innmelder": "Stage 1 · Reporter",
 "Ledd 2 · Behandler": "Stage 2 · Handler",
 "Godkjenningsforløp": "Approval workflow",
 "RØR": "PLB",
 "FAG": "TRD",
 "BH": "CL",
 "HMS": "Safety",
 "Scenario: Enkel oppgave mellom TE og fag": "Scenario: Simple task between the main contractor and a trade",
 "TE oppdager en feil i tavlerommet og oppretter en oppgave til Elektriker. Oppgaven løses direkte i ett forløp uten å involvere andre fag.": "The main contractor finds a fault in the switch room and creates a task for the Electrician. The task is resolved directly in one workflow without involving other trades.",
 "Forløp: TE → Elektriker": "Workflow: MC → Electrician",
 "TE → Elektriker": "MC → Electrician",
 "TE oppretter oppgave": "Main contractor creates a task",
 "TE oppdager feilen i tavlerommet og registrerer den som en ny oppgave til Elektriker, legger ved bilde og plasserer på plantegningen.": "The main contractor finds the fault in the switch room and registers it as a new task for the Electrician, attaches a photo and places it on the floor plan.",
 "Feil i tavlerom 1. etg": "Fault in switch room, 1st floor",
 "Opprettet av TE, nå": "Created by MC, just now",
 "Elektriker mottar og vurderer": "Electrician receives and assesses",
 "Elektriker ser oppgaven i sin innboks og vurderer omfanget av feilen.": "The Electrician sees the task in their inbox and assesses the extent of the fault.",
 "Mottatt": "Received",
 "Hos Elektriker, under vurdering": "With Electrician, being assessed",
 "Elektriker utbedrer": "Electrician fixes it",
 "Elektriker utfører reparasjonen, dokumenterer med bilder og sender oppgaven tilbake til TE.": "The Electrician carries out the repair, documents it with photos and sends the task back to the main contractor.",
 "Utbedret": "Fixed",
 "Elektriker: \"Ferdig utført, se vedlagte bilder\"": "Electrician: \"Done, see attached photos\"",
 "Oppgave godkjent og lukket": "Task approved and closed",
 "TE kontrollerer, godkjenner og lukker oppgaven. Hele historikken er dokumentert med bilder, kommentarer og tidsstempler.": "The main contractor checks, approves and closes the task. The whole history is documented with photos, comments and timestamps.",
 "Lukket ✓": "Closed ✓",
 "Lukket av TE, total tid: 2 dager": "Closed by MC, total time: 2 days",
 "Scenario: Oppgave sendes til annet forløp": "Scenario: Task sent on to another workflow",
 "Rørlegger oppdager at et ventilasjonsrør kolliderer med planlagt rørtrasé i 2. etasje. Oppgaven sendes til TE i forløp 1. TE sender den videre i forløp 2 til ventilasjon. Forutsetning: Samme oppgavetype må være aktivert i begge forløp for at oppgaven skal kunne flyttes.": "The Plumber finds that a ventilation duct clashes with the planned pipe route on the 2nd floor. The task is sent to the main contractor in workflow 1. The main contractor sends it on in workflow 2 to Ventilation. Requirement: The same task type must be enabled in both workflows for the task to be moved.",
 "Forløp 1: Rørlegger → TE": "Workflow 1: Plumber → MC",
 "Forløp 2: TE → Ventilasjon": "Workflow 2: MC → Ventilation",
 "Rørlegger → TE": "Plumber → MC",
 "TE → Ventilasjon": "MC → Ventilation",
 "Rørlegger oppretter oppgave": "Plumber creates a task",
 "Rørlegger registrerer kollisjonen som en ny oppgave i oppgaveforløpet, legger ved bilde og plasserer den på plantegningen.": "The Plumber registers the clash as a new task in the task workflow, attaches a photo and places it on the floor plan.",
 "Kollisjon ventilasjon/rør 2. etg": "Clash ventilation/pipes, 2nd floor",
 "Opprettet av Rørlegger, nå": "Created by Plumber, just now",
 "TE mottar og vurderer": "Main contractor receives and assesses",
 "Totalentreprenøren ser oppgaven i sin innboks, vurderer situasjonen og ser at det er ventilasjonsrøret som må legges om.": "The main contractor sees the task in their inbox, assesses the situation and sees that it is the ventilation duct that has to be rerouted.",
 "Hos TE, under vurdering": "With MC, being assessed",
 "TE sender oppgave i nytt forløp": "Main contractor sends the task in a new workflow",
 "TE sender oppgaven videre i forløp 2 (TE → Ventilasjon) med instruksjoner om å legge om ventilasjonsrøret iht. revidert tegning. Dette er mulig fordi samme oppgavetype er aktivert i begge forløp. Rørlegger som opprettet den opprinnelige oppgaven har fortsatt innsyn og kan følge fremdriften, men kan ikke editere oppgaven når den ligger i et forløp de ikke har rettigheter i.": "The main contractor sends the task on in workflow 2 (MC → Ventilation) with instructions to reroute the ventilation duct according to the revised drawing. This is possible because the same task type is enabled in both workflows. The Plumber who created the original task can still see it and follow progress, but cannot edit the task while it is in a workflow they have no rights in.",
 "Ny i forløp 2": "New in workflow 2",
 "TE: \"Legg om trasé iht. vedlagt revidert tegning\" · 👁️ Rørlegger følger med": "MC: \"Reroute according to the attached revised drawing\" · 👁️ Plumber is following",
 "Ventilasjon utbedrer": "Ventilation fixes it",
 "Ventilasjon utfører omleggingen, tar bilde av ferdig resultat og sender oppgaven tilbake til TE.": "Ventilation carries out the rerouting, takes a photo of the result and sends the task back to the main contractor.",
 "Ventilasjon: \"Ferdig utført, se vedlagt bilde\"": "Ventilation: \"Done, see attached photo\"",
 "TE kontrollerer": "Main contractor checks",
 "TE mottar oppgaven tilbake i forløp 2, kontrollerer at ventilasjonsrøret er lagt om korrekt og godkjenner.": "The main contractor gets the task back in workflow 2, checks that the ventilation duct has been rerouted correctly and approves it.",
 "Til kontroll": "For review",
 "Hos TE, venter på godkjenning": "With MC, waiting for approval",
 "TE godkjenner utbedringen og lukker oppgaven i forløp 2. Kollisjonen er løst, alt er dokumentert med bilder, kommentarer og tidsstempler.": "The main contractor approves the fix and closes the task in workflow 2. The clash is resolved, and everything is documented with photos, comments and timestamps.",
 "Lukket av TE, total tid: 3 dager": "Closed by MC, total time: 3 days",
 "Scenario: Fra HMS-observasjon til HMS-oppgave": "Scenario: From safety observation to safety issue",
 "En fagarbeider melder inn en HMS-observasjon. Denne er privat og går som standard til HMS-lederne. De kvalitetssikrer innholdet, kategoriserer, og kan basert på observasjonen opprette en HMS-oppgave som sendes i et eget HMS-forløp.": "A tradesperson reports a safety observation. It is private and goes to the safety managers by default. They check the content, categorise it, and based on the observation can create a safety issue that is sent in its own safety workflow.",
 "🔒 HMS-observasjon (privat)": "🔒 Safety observation (private)",
 "HMS-oppgaveforløp": "Safety issue workflow",
 "🔒 Privat*": "🔒 Private*",
 "HMS-leder → Fag": "Safety manager → Trade",
 "Fagarbeider melder HMS-observasjon": "Tradesperson reports a safety observation",
 "Fagarbeider oppdager manglende sikring ved stillas i 3. etasje og registrerer en HMS-observasjon med bilde og plassering. Observasjonen er privat og synlig for HMS-lederne.": "A tradesperson finds missing guarding on the scaffolding on the 3rd floor and registers a safety observation with a photo and location. The observation is private and visible to the safety managers.",
 "Ny observasjon": "New observation",
 "Manglende sikring stillas 3. etg": "Missing scaffold guarding, 3rd floor",
 "Privat melding til HMS-ledere": "Private report to safety managers",
 "HMS-ledere kvalitetssikrer": "Safety managers check it",
 "HMS-lederne mottar observasjonen privat. De vurderer alvorlighetsgrad, kategoriserer som \"Fall fra høyde\", og kan fjerne upassende innhold før videre behandling. Som standard er det bare HMS-lederne som har innsyn.": "The safety managers receive the observation privately. They assess the severity, categorise it as \"Fall from height\", and can remove inappropriate content before it is handled further. By default only the safety managers can see it.",
 "Under vurdering": "Being assessed",
 "🔒 Privat. Kategori: Fall fra høyde. Alvorlighet: Høy": "🔒 Private. Category: Fall from height. Severity: High",
 "HMS-ledere beslutter tiltak": "Safety managers decide on action",
 "Basert på observasjonen beslutter HMS-lederne at det må opprettes en egen HMS-oppgave. Observasjonen forblir privat, men HMS-oppgaven blir synlig i HMS-forløpet.": "Based on the observation, the safety managers decide that a separate safety issue must be created. The observation stays private, but the safety issue becomes visible in the safety workflow.",
 "Tiltak besluttet": "Action decided",
 "Beslutning: Opprett HMS-oppgave for utbedring": "Decision: Create a safety issue to be fixed",
 "HMS-oppgave opprettes i HMS-forløp": "Safety issue created in the safety workflow",
 "HMS-lederne oppretter en separat HMS-oppgave basert på observasjonen og tildeler den til faget med krav om umiddelbar utbedring.": "The safety managers create a separate safety issue based on the observation and assign it to the trade, requiring an immediate fix.",
 "Ny HMS-oppgave": "New safety issue",
 "Utbedr sikring stillas 3. etg": "Fix scaffold guarding, 3rd floor",
 "HMS: \"Sikring må monteres før videre arbeid\"": "Safety: \"Guarding must be fitted before work continues\"",
 "Fag utbedrer": "Trade fixes it",
 "Faget mottar HMS-oppgaven, monterer sikring på stillaset, dokumenterer med bilder og sender oppgaven tilbake til HMS-lederne.": "The trade receives the safety issue, fits guarding to the scaffolding, documents it with photos and sends the issue back to the safety managers.",
 "Fag: \"Sikring montert, se vedlagte bilder\"": "Trade: \"Guarding fitted, see attached photos\"",
 "HMS-oppgave godkjent og lukket": "Safety issue approved and closed",
 "HMS-lederne kontrollerer utbedringen, godkjenner og lukker HMS-oppgaven. Den opprinnelige observasjonen er ferdigbehandlet.": "The safety managers check the fix, approve it and close the safety issue. The original observation has been fully handled.",
 "Lukket av HMS-leder, total tid: 1 dag": "Closed by safety manager, total time: 1 day",
 "Som standard ser bare HMS-lederne observasjonene. Avhengig av oppsett kan to andre grupper også få innsyn: Oppgave- og sjekklistekoordinator og Field-observatører.": "By default only the safety managers see the observations. Depending on the setup, two other groups can also see them: Task and checklist coordinator and Field observers.",
 "Scenario: Endringsmelding med godkjenning": "Scenario: Change notice with approval",
 "Underentreprenør varsler en endring som må behandles i flere ledd. Hvert ledd kan ha egne felter som settes opp i malen. Felter kan flyttes til ett spesifikt ledd (kun redigerbare der) eller kopieres til flere ledd (redigerbare i alle). TE (Ledd 2) kan sende videre til godkjenning hos byggherre, eller lukke saken som \"Omtvistet\" ved uenighet.": "A subcontractor reports a change that has to be handled in several stages. Each stage can have its own fields, set up in the template. Fields can be moved to one specific stage (editable only there) or copied to several stages (editable in all of them). The main contractor (stage 2) can send it on to the client for approval, or close the case as \"Disputed\" if the parties disagree.",
 "Ledd 1: UE varsler": "Stage 1: SC reports",
 "Ledd 2: TE behandler": "Stage 2: MC handles",
 "Ledd 3: BH godkjenner": "Stage 3: Client approves",
 "UE → TE → Byggherre": "SC → MC → Client",
 "UE varsler endringsmelding (Ledd 1)": "Subcontractor submits a change notice (stage 1)",
 "Underentreprenør registrerer en endringsmelding: \"Fundamenttykkelse må økes pga. grunnforhold\". Legger ved dokumentasjon og beskrivelse av endringen.": "The subcontractor registers a change notice: \"Foundation thickness must be increased due to ground conditions\". Attaches documentation and a description of the change.",
 "Endringsmelding: Økt fundamenttykkelse": "Change notice: Thicker foundation",
 "Varslet av UE (Ledd 1), nå": "Reported by SC (stage 1), just now",
 "TE ser mangler, sender tilbake (Ledd 2 → 1)": "Main contractor finds gaps and sends it back (stage 2 → 1)",
 "TE mottar endringsvarselet i ledd 2, men ser at det mangler geoteknisk rapport. Sender oppgaven tilbake til ledd 1 med kommentar. Oppgaven kan sendes tilbake til alle tidligere ledd.": "The main contractor receives the change notice in stage 2 but sees that the geotechnical report is missing. Sends it back to stage 1 with a comment. The case can be sent back to any earlier stage.",
 "Returnert til Ledd 1": "Returned to stage 1",
 "TE: \"Mangler geoteknisk rapport, vennligst legg ved\"": "MC: \"Geotechnical report missing, please attach\"",
 "UE oppdaterer og sender på nytt (Ledd 1 → 2)": "Subcontractor updates and resubmits (stage 1 → 2)",
 "UE legger ved geoteknisk rapport og oppdatert kostnadstilbud, og sender endringsvarselet tilbake til ledd 2.": "The subcontractor attaches the geotechnical report and an updated cost quote, and sends the change notice back to stage 2.",
 "Oppdatert": "Updated",
 "UE: \"Geoteknisk rapport vedlagt + oppdatert tilbud\"": "SC: \"Geotechnical report attached + updated quote\"",
 "TE fyller ut leddspesifikke felter (Ledd 2)": "Main contractor fills in stage-specific fields (stage 2)",
 "TE fyller inn feltene som er konfigurert for dette leddet i malen: estimert kostnad, konsekvens for fremdrift, og anbefaling. TE kan nå sende videre til byggherre for godkjenning, eller markere saken som \"Omtvistet\" dersom partene er uenige.": "The main contractor fills in the fields configured for this stage in the template: estimated cost, impact on schedule, and recommendation. The main contractor can now send it on to the client for approval, or mark the case as \"Disputed\" if the parties disagree.",
 "Sendt til Ledd 3": "Sent to stage 3",
 "Kostnad: 450 000 kr · Konsekvens: +2 uker · Anbefaling: Godkjenn": "Cost: NOK 450,000 · Impact: +2 weeks · Recommendation: Approve",
 "Byggherre vurderer (Ledd 3)": "Client assesses (stage 3)",
 "Byggherre gjennomgår endringsmeldingen med all dokumentasjon og TEs vurdering. Kan godkjenne endringen, eller sende tilbake til ledd 1 eller 2 for mer informasjon.": "The client reviews the change notice with all documentation and the main contractor’s assessment. They can approve the change, or send it back to stage 1 or 2 for more information.",
 "Til godkjenning": "For approval",
 "Hos Byggherre (Ledd 3), venter på beslutning": "With Client (stage 3), waiting for a decision",
 "Endringsmelding godkjent": "Change notice approved",
 "Byggherre godkjenner endringen. Hele historikken med alle ledd, kommentarer, vedlegg og leddspesifikke felter er dokumentert.": "The client approves the change. The whole history, with every stage, comment, attachment and stage-specific field, is documented.",
 "Godkjent ✓": "Approved ✓",
 "Godkjent av Byggherre. Kostnad: 450 000 kr · +2 uker": "Approved by Client. Cost: NOK 450,000 · +2 weeks",
 "Velg tema": "Choose a topic",
 "Samhandling i Box": "Collaboration in Box",
 "Enkel deling og kommunikasjon rundt dokumenter i prosjektet": "Simple sharing and communication around the project’s documents",
 "Mappestruktur og filhåndtering": "Folder structure and file management",
 "Hold mappene flate, og la metadata styre filtrering og navngiving": "Keep folders flat, and let metadata drive filtering and naming",
 "Full CDE-oppsett med statusområder, innsendinger og godkjenningsflyt": "A full CDE setup with status areas, submittals and approval flows",
 "Oppsett": "Setup",
 "Statuser": "Statuses",
 "Kommentar: opprett, send, lukk": "Comment: create, send, close",
 "I Dalux Box oppretter du": "In Dalux Box you create",
 "kommentarer": "comments",
 "direkte på tegninger, PDF-er og BIM-modeller. Hver kommentar tilhører en": "directly on drawings, PDFs and BIM models. Each comment belongs to a",
 "kommunikasjonsflyt": "communication channel",
 "som styrer hvilke grupper som kan se, opprette, redigere og lukke den. Slik sørger flyten for at riktig informasjon når riktige personer, og at all dialog er sporbar.": "that controls which groups can view, create, edit and close it. That way the channel makes sure the right information reaches the right people, and that every conversation can be traced.",
 "Brukergrupper og rettigheter": "User groups and rights",
 "Hver kommunikasjonsflyt inneholder brukergrupper med egne rettigheter:": "Each communication channel contains user groups with their own rights:",
 "Les": "View",
 "Rediger": "Edit",
 "og": "and",
 "Lukk": "Close",
 ". Tenk nøye gjennom hvem som trenger hvilke rettigheter. De med Rediger-rettighet kan oppdatere status og sende kommentarer videre. Lukk-rettigheten avgjør hvem som kan avslutte saker, og dette varierer per flyt: i en prosjekteringsflyt kan det være prosjekteringsleder, mens i en byggherreflyt er det typisk byggherre selv.": ". Think carefully about who needs which rights. People with Edit rights can update the status and pass comments on. The Close right decides who can close cases, and this varies by channel: in a design channel it might be the project planning manager, while in a client channel it is usually the client.",
 "Kommentartyper": "Comment types",
 "Du kan knytte hver": "You can link each",
 "kommentartype": "comment type",
 "til én eller flere flyter. Kommentartypene kan ha egendefinerte felter (tekst, nedtrekklister, tallverdier) og egne statusverdier med fargekoder. Definer kommentartypene etter prosjektets behov, f.eks. «Prosjektering», «RFI» eller «Byggherreavklaring».": "to one or more channels. Comment types can have custom fields (text, drop-down lists, numbers) and their own status values with colour codes. Define comment types to fit the project, for example “Design”, “RFI” or “Client clarification”.",
 "Egendefinerte statuser": "Custom statuses",
 "Bruk": "Use",
 "egendefinerte statuser": "custom statuses",
 "med fargekoder for å vise fremdrift. Alle med Rediger-rettighet kan oppdatere status når kommentaren sendes mellom grupper. Statusendringer loggføres automatisk i kommentarens aktivitetslogg, slik at hele historikken er sporbar.": "with colour codes to show progress. Anyone with Edit rights can update the status as the comment moves between groups. Status changes are logged automatically in the comment’s activity log, so the whole history can be traced.",
 "Åpen dialog": "Open dialogue",
 "Alle brukergrupper med rettigheter kan sende kommentarer til hvem som helst i flyten, både til grupper og enkeltpersoner. Kommentaren kan bevege seg fritt mellom gruppene til den lukkes.": "Every user group with rights can send comments to anyone in the channel, both groups and individuals. The comment can move freely between groups until it is closed.",
 "Full sporbarhet": "Full traceability",
 "Hver kommentar har en komplett": "Every comment has a complete",
 "aktivitetslogg": "activity log",
 ": statusendringer, meldinger, vedlegg og hvem som gjorde hva. Kommentaren forblir knyttet til tegningen eller dokumentet den ble opprettet på.": ": status changes, messages, attachments and who did what. The comment stays linked to the drawing or document it was created on.",
 "Lukking av kommentarer": "Closing comments",
 "Den gruppen som har Lukk-rettighet i flyten avslutter kommentaren når saken er ferdigbehandlet. I dette eksempelet er det Prosjekteringsleder, men det kan like gjerne være Byggherre i en annen flyt. Lukket betyr ikke slettet: all historikk, vedlegg og meldinger bevares permanent.": "The group with the Close right in the channel closes the comment when the case is resolved. In this example it is the Project planning manager, but in another channel it could just as well be the Client. Closed does not mean deleted: all history, attachments and messages are kept permanently.",
 "Uten egendefinerte statuser": "Without custom statuses",
 "Dag 1": "Day 1",
 "Aktivert": "Active",
 "⋮ 4 dager stillhet": "⋮ 4 days of silence",
 "Dag 5": "Day 5",
 "Lukket": "Closed",
 "\"Hva skjedde i mellom?\"": "\"What happened in between?\"",
 "Med egendefinerte statuser": "With custom statuses",
 "Ny": "New",
 "Dag 2": "Day 2",
 "Under behandling": "In progress",
 "Dag 3": "Day 3",
 "Besvart": "Answered",
 "\"Hele løpet er sporbart\"": "\"The whole process can be traced\"",
 "Eksempler på status-oppsett": "Example status setups",
 "Start med standardflyten. Tilpass bare når kommentartypen krever det.": "Start with the standard flow. Only adapt it when the comment type needs it.",
 "Anbefalt utgangspunkt": "Recommended starting point",
 "Standardflyt": "Standard flow",
 "Brukes for de fleste kommentartyper. Hold på dette så langt det går for å få konsistens på tvers av prosjektet.": "Used for most comment types. Stick to it as far as you can to keep the project consistent.",
 "Når kommentartypen krever det": "When the comment type needs it",
 "Request for Information. Litt annerledes flyt, så egne statuser gir mening her.": "Request for Information. A slightly different flow, so its own statuses make sense here.",
 "Spurt": "Asked",
 "Under utredning": "Being investigated",
 "Avklart": "Clarified",
 "Byggherreavklaring": "Client clarification",
 "Saker som krever byggherrens beslutning. Statusene speiler beslutningsløpet.": "Cases that need the client’s decision. The statuses mirror the decision process.",
 "Avventer BH": "Waiting for client",
 "Besvart av BH": "Answered by client",
 "Utført": "Done",
 "Tre prinsipper når du setter opp statuser": "Three principles for setting up statuses",
 "Prinsipp 1": "Principle 1",
 "Standardiser hvor det er mulig": "Standardise where possible",
 "Bruk samme status-navn og fargekoder på tvers av kommentartyper. Det gjør oversikten lettere og folk lærer mønsteret raskere.": "Use the same status names and colour codes across comment types. It makes the overview easier and people learn the pattern faster.",
 "Prinsipp 2": "Principle 2",
 "Hold det håndterbart": "Keep it manageable",
 "3 til 5 statuser per kommentartype er nok. Flere gjør det vanskeligere å holde orden, og hver enkelt status mister verdi.": "3 to 5 statuses per comment type is enough. More makes it harder to keep track, and each status loses value.",
 "Prinsipp 3": "Principle 3",
 "Dekk hele løpet": "Cover the whole process",
 "Ha statuser som dekker fra \"Ny\" til \"Lukket\", ikke bare midten. Da ser du både hvor saken starter og når den faktisk er ferdig.": "Have statuses that cover everything from \"New\" to \"Closed\", not just the middle. Then you can see both where a case starts and when it is actually finished.",
 "Status-endringer logges automatisk i aktivitetsloggen. Se hva som skjer med en kommentar steg for steg på fanen": "Status changes are logged automatically in the activity log. See what happens to a comment step by step on the tab",
 "Prosjekteringsgruppe": "Design group",
 "Kommentartyper:": "Comment types:",
 "Kommentar, Prosjektering": "Comment, Design",
 "· Lukkes av:": "· Closed by:",
 "Prosjekteringsleder": "Project planning manager",
 "Prosjekterings­leder": "Planning manager",
 "Lukker kommentarer": "Closes comments",
 "Kommunikasjonsflyten viser hvilke grupper som kan kommunisere sammen": "The communication channel shows which groups can communicate with each other",
 "Følg kommentaren mellom gruppene. Den lukkes av Prosjekteringsleder": "Follow the comment between the groups. It is closed by the Project planning manager",
 "Rådgivende ingeniør bygg": "Structural engineer",
 "Rådgivende ingeniør elektro": "Electrical engineer",
 "Rådgivende ingeniør VVS": "HVAC engineer",
 "Totalentreprise": "Main contract",
 "Arkitekt": "Architect",
 "Tom gruppe": "Empty group",
 "En kommentar i Box starter når du markerer et punkt på en tegning, et dokument eller en BIM-modell, og fyller ut kommentarskjemaet. Den lever videre gjennom hele behandlingen, med full sporbarhet i aktivitetsloggen.": "A comment in Box starts when you mark a point on a drawing, a document or a BIM model and fill in the comment form. It lives on through the whole process, fully traceable in the activity log.",
 "Opprett": "Create",
 "Dialog": "Dialogue",
 "Opprett kommentar:": "Create a comment:",
 "Velg fil (tegning, PDF eller BIM-modell) og marker med sky, pil, tekst eller måling. Fyll ut kommentarskjema med type, kommunikasjonsflyt, tittel, tidsfrist og beskrivelse. Kommentaren knyttes permanent til filen og posisjonen.": "Choose a file (drawing, PDF or BIM model) and mark it up with a cloud, arrow, text or measurement. Fill in the comment form with type, communication channel, title, deadline and description. The comment is permanently linked to the file and the position.",
 "Send til gruppe eller person:": "Send to a group or a person:",
 "Du sender kommentaren til en gruppe eller en person i flyten. Mottakeren får varsel, og kommentaren dukker opp på tegningen med en fargekode som viser statusen.": "You send the comment to a group or a person in the channel. The recipient is notified, and the comment appears on the drawing with a colour code that shows its status.",
 "Dialog og statusoppdatering:": "Dialogue and status updates:",
 "Mottakeren svarer med meldinger og vedlegg i kommentartråden. Statusen oppdateres underveis, f.eks. fra «Under behandling» til «Besvart». Du kan sende kommentaren videre til andre grupper i flyten hvis det trengs.": "The recipient replies with messages and attachments in the comment thread. The status is updated along the way, for example from “In progress” to “Answered”. You can send the comment on to other groups in the channel if needed.",
 "Lukking:": "Closing:",
 "Når saken er ferdigbehandlet, lukker en bruker med Lukk-rettighet kommentaren. Hvem dette er avhenger av flyten, og det kan være prosjekteringsleder, byggherre eller en annen rolle. All historikk bevares: statusendringer, meldinger, vedlegg og tidsstempler.": "When the case is resolved, a user with Close rights closes the comment. Who that is depends on the channel: it can be the project planning manager, the client or another role. All history is kept: status changes, messages, attachments and timestamps.",
 "📄 D-Plan 01 · Kommentar #71": "📄 D-Plan 01 · Comment #71",
 "RiE": "ELE",
 "ARK": "ARC",
 "RiB": "STR",
 "RiV": "HVAC",
 "Prosj.leder": "Planning mgr.",
 "Eksempel: Aktivitetslogg for kommentar": "Example: Activity log for a comment",
 "Kommentar #71 - «Kollisjon mellom kabelbroer og ventilasjonskanal» på plantegning D-Plan 01": "Comment #71 - “Clash between cable trays and ventilation duct” on floor plan D-Plan 01",
 "10. des. 2024": "10 Dec 2024",
 "12. des. 2024": "12 Dec 2024",
 "13. des. 2024": "13 Dec 2024",
 "15. des. 2024": "15 Dec 2024",
 "Opprettet kommentar i flyt: Prosjekteringsgruppe": "Created comment in channel: Design group",
 "Ansvarlig gruppe satt til: RiE (Rådgivende ingeniør elektro)": "Responsible group set to: ELE (Electrical engineer)",
 "Meldingsmottakere lagt til: Ole Ventansen, Tor Ampere": "Notified users added: Ole Ventansen, Tor Ampere",
 "Ny melding: «Ser kollisjonen. Kan flytte kabelbroene 200mm nord, men trenger bekreftelse fra ARK på takhøyde.»": "New message: “I see the clash. We can move the cable trays 200 mm north, but need ARC to confirm the ceiling height.”",
 "Vedlegg lagt til:": "Attachment added:",
 "Kabelbroer_alternativ_trasé.pdf": "Cable_trays_alternative_route.pdf",
 "Ansvarlig gruppe endret til: ARK (Arkitekt)": "Responsible group changed to: ARC (Architect)",
 "Status oppdatert fra": "Status updated from",
 "til": "to",
 "Ny melding: «Takhøyde OK. Fri høyde 2400mm opprettholdes med ny trasé.»": "New message: “Ceiling height OK. 2400 mm clear height is kept with the new route.”",
 "Ansvarlig gruppe endret til: Prosjekteringsleder": "Responsible group changed to: Project planning manager",
 "Ny melding: «Løsning godkjent. RiE oppdaterer modell innen rev. 3.»": "New message: “Solution approved. ELE updates the model by rev. 3.”",
 "Mappestruktur og metadata": "Folder structure and metadata",
 "Filer og versjonshåndtering": "Files and versioning",
 "Få mer ut av Box: hold mappene flate, og la metadata gjøre jobben med å finne filer.": "Get more out of Box: keep folders flat, and let metadata do the work of finding files.",
 "Mappestruktur": "Folder structure",
 "Navngiving og metadata": "Naming and metadata",
 "Filtrering i praksis": "Filtering in practice",
 "Mange bygger en tung mappestruktur for å organisere filer. I Box holder du i stedet strukturen": "Many people build a heavy folder structure to organise files. In Box you instead keep the structure",
 "så flat som mulig": "as flat as possible",
 "og lar metadata styre filtrering, sortering og navigering.": "and let metadata drive filtering, sorting and navigation.",
 "Før": "Before",
 "Tung mappestruktur": "Heavy folder structure",
 "Mappe i mappe i mappe. Du må vite nøyaktig hvor en fil ligger for å finne den, og samme fil havner gjerne flere steder.": "Folder in folder in folder. You need to know exactly where a file is to find it, and the same file often ends up in several places.",
 "I Box": "In Box",
 "Flat struktur + metadata": "Flat structure + metadata",
 "Få mapper. Hvert felt i filnavnet blir metadata du filtrerer og sorterer på. Du finner filer ved å søke, ikke ved å lete.": "Few folders. Each field in the file name becomes metadata you filter and sort on. You find files by searching, not by hunting.",
 "Mapper du faktisk trenger": "Folders you actually need",
 "To ting avgjør om en mappe hører hjemme i prosjektet:": "Two things decide whether a folder belongs in the project:",
 "Rettigheter": "Rights",
 "Rettigheter styres gjennom brukergruppene, de samme i alle Dalux-moduler. Du gir hver gruppe tilgang til mappene: hvem som får lese, og hvem som får laste opp og redigere. Ofte går fagene igjen på både mappe- og gruppenivå, men ikke alltid.": "Rights are managed through user groups, the same in every Dalux module. You give each group access to folders: who can read, and who can upload and edit. Trades often appear at both folder and group level, but not always.",
 "Maler for navngiving": "File naming templates",
 "Hver mappe kan ha sin egen navnemal. Da fyller Box ut metadata automatisk når du laster opp, riktig for akkurat det faget. Hold deg til én regel per mappe.": "Each folder can have its own naming template. Box then fills in metadata automatically when you upload, correctly for that trade. Stick to one rule per folder.",
 "Unngå fasemapper": "Avoid phase folders",
 "Lager du en mappe per fase, dupliserer du filer, og det blir uklart hva som er nyest. Bruk": "If you make a folder per phase, you duplicate files, and it becomes unclear what is newest. Use",
 "versjonssett": "version sets",
 "i stedet. Mer om det på Side 2: Filer og versjonshåndtering.": "instead. More on that on Page 2: Files and versioning.",
 "Navngiving trenger ikke være komplisert": "Naming doesn’t have to be complicated",
 "Navnemalen deler filnavnet i metadata ved opplasting. Et avgrensningstegn skiller hvert felt. Bindestrek og understrek er vanligst, mellomrom fungerer til tider, og egentlig kan de fleste tegn brukes så lenge malen er satt opp for det. Velg så enkelt eller detaljert du vil.": "The naming template splits the file name into metadata on upload. A delimiter separates each field. Hyphens and underscores are most common, spaces sometimes work, and in fact most characters can be used as long as the template is set up for it. Make it as simple or as detailed as you like.",
 "Enkel": "Simple",
 "Detaljert": "Detailed",
 "Tegningsnavn": "Drawing name",
 "Inndelt": "Split",
 "Fag (bokstav)": "Trade (letter)",
 "VVS": "Mechanical",
 "Elektro": "Electrical",
 "Utendørs": "Outdoor",
 "RIBrann": "Fire",
 "Etasje": "Floor",
 "Underetasje": "Basement",
 "Plan 1. etasje": "Floor 1",
 "Plan 2. etasje": "Floor 2",
 "Takplan 1": "Roof plan 1",
 "Takplan 2": "Roof plan 2",
 "Type tegning": "Drawing type",
 "Plantegning": "Floor plan",
 "Komplettering": "Completion",
 "Snitt, fasade": "Section, elevation",
 "Detaljer": "Details",
 "Prinsipp": "Schematic",
 "Systemkode": "System code",
 "RIV rør": "HVAC pipes",
 "RIV vent": "HVAC vent",
 "Standardfelter og egne felter": "Standard fields and your own fields",
 "Dalux har et sett standardfelter som går igjen i alle prosjekter. De fleste feltene vi nettopp splittet filnavnet i, er derimot metadata på filnivå som du selv har lagt til.": "Dalux has a set of standard fields that appear in every project. Most of the fields we just split the file name into, however, are file-level metadata that you added yourself.",
 "Standardfelter (allerede i Dalux)": "Standard fields (already in Dalux)",
 "Felt som Filnavn, Versjon, Tittel, Status, Firma og Nummer ligger i Dalux fra før, merket med et låsesymbol. Noen av dem er låst til bestemte deler av systemet og kan ikke brukes som metadata i Box.": "Fields such as File name, Version, Title, Status, Company and Number already exist in Dalux, marked with a lock symbol. Some of them are locked to specific parts of the system and cannot be used as metadata in Box.",
 "Egne felter (du lager dem)": "Your own fields (you create them)",
 "Fag, etasje, type, systemkode og løpenummer er felt du legger til selv på filnivå. Det er disse navnemalen fyller ut automatisk når du laster opp.": "Trade, floor, type, system code and serial number are fields you add yourself at file level. These are the ones the naming template fills in automatically when you upload.",
 "Slik bygger du malen": "How to build the template",
 "For de som vil sette opp navngiving selv: i malen drar du inn feltene du vil ha, med en avgrenser mellom hver.": "For those who want to set up naming themselves: in the template you drag in the fields you want, with a delimiter between each.",
 "Felt og avgrensere": "Fields and delimiters",
 "Hvert felt henter du fra metadatalista du har laget. Et felt kan være tekst, dato eller et valg fra en liste. Du kan også styre om det bare skal være tall, og hvor langt det skal være.": "Each field comes from the metadata list you created. A field can be text, a date or a choice from a list. You can also control whether it should be numbers only, and how long it should be.",
 "Test før du lagrer": "Test before you save",
 "Du trenger ikke bruke alle mulighetene. Vil du prøve, kan du teste hvordan et filnavn blir før du tar malen i bruk.": "You don’t need to use every option. If you want to try, you can test what a file name will look like before you start using the template.",
 "«Nummer» kobler filene automatisk": "“Number” links the files automatically",
 "Ett av standardfeltene": "One of the standard fields",
 "«Nummer» er ett av standardfeltene, ikke noe du lager selv. Det er tekststrengen Dalux matcher på for automatiske hyperlenker. Klikker du et nummer i en tegning, hopper du rett til riktig fil.": "“Number” is one of the standard fields, not something you create. It is the text string Dalux matches for automatic hyperlinks. Click a number in a drawing and you jump straight to the right file.",
 "Må være unikt": "Must be unique",
 "Er nummeret ikke unikt, kobler Dalux til første treff, og du havner på feil fil. Lenkene virker også fra Lokasjoner og fra felt-appen, og bare til filer du har tilgang til.": "If the number is not unique, Dalux links to the first match, and you end up on the wrong file. The links also work from Locations and from the field app, and only to files you have access to.",
 "Slik bruker du det i Box": "How to use it in Box",
 "Når filene har metadata, filtrerer og søker du i stedet for å lete i mapper. Her spiller det ingen rolle om metadataen kom fra en navnemal eller ble fylt inn for hånd, så lenge den er der.": "When files have metadata, you filter and search instead of hunting through folders. It doesn’t matter whether the metadata came from a naming template or was filled in by hand, as long as it is there.",
 "Nummer": "Number",
 "Samme metadata driver": "The same metadata drives the",
 "hyperlenkene": "hyperlinks",
 ": klikk et nummer i en tegning, og du hopper rett til riktig fil.": ": click a number in a drawing and you jump straight to the right file.",
 "Denne delen er ikke ferdig ennå.": "This part isn’t finished yet.",
 "Når den er klar vil den dekke versjonssett som erstatter fasemapper, sammenligning mot tidligere versjoner, Microsoft 365, og publisering fra Filer til Utgitte filer.": "When it is ready it will cover version sets instead of phase folders, comparison with earlier versions, Microsoft 365, and publishing from Files to Published files.",
 "Versjonssett i stedet for fasemapper": "Version sets instead of phase folders",
 "Sammenligning mot tidligere versjoner": "Comparison with earlier versions",
 "Publisering til Utgitte filer": "Publishing to Published files",
 "← Tilbake til Side 1": "← Back to Page 1",
 "Fundamentplan": "Foundation plan",
 "er standard-feltet Dalux bruker til automatiske koblinger. Hold det unikt, så lenker tegninger og dokumenter seg selv.": "is the standard field Dalux uses for automatic links. Keep it unique, and drawings and documents link themselves.",
 "Alle": "All",
 "Takplan": "Roof plan",
 "Fasade": "Elevation",
 "Fasade sør": "South elevation",
 "Snitt": "Section",
 "Snitt B-B": "Section B-B",
 "Detalj": "Detail",
 "Detalj inngangsparti": "Entrance detail",
 "Skjema": "Schedule",
 "Dørskjema": "Door schedule",
 "Fundament underetasje": "Basement foundation",
 "Dekkeplan 1. etasje": "Slab plan, level 1",
 "Fundamentplan 2. etasje": "Foundation plan, level 2",
 "Snitt A-A": "Section A-A",
 "Armeringsdetalj": "Reinforcement detail",
 "Ventilasjon underetasje": "Ventilation, basement",
 "Ventilasjon 2. etasje": "Ventilation, level 2",
 "Prinsipp røropplegg": "Piping schematic",
 "Ventilasjonsskjema": "Ventilation schedule",
 "Kursopplegg 1. etasje": "Circuit layout, level 1",
 "Belysning 2. etasje": "Lighting, level 2",
 "Strømskjema": "Power schematic",
 "Prinsipp nødlys": "Emergency lighting schematic",
 "Viser": "Showing",
 "av 20 tegninger": "of 20 drawings",
 "Ingen treff": "No matches",
 "Bygg": "Building",
 "Løpenr": "Serial no.",
 "Plantegning 2. etasje": "Floor plan, level 2",
 "Flere avgrensere = flere metadatafelt å filtrere og sortere på. For hyperlenking holder det med ett unikt": "More delimiters = more metadata fields to filter and sort on. For hyperlinks, one unique",
 ", som i Enkel.": "is enough, as in Simple.",
 "Box i praksis": "Box in practice",
 "Dokumentflyt": "Document flow",
 "Internasjonal standard for informasjonshåndtering i bygge- og anleggsprosjekter": "The international standard for information management in construction projects",
 "ISO 19650 handler om å sørge for at riktig informasjon er tilgjengelig for riktige personer til rett tid. Standarden setter rammene for hvordan dokumenter og modeller skal organiseres, navngis, deles og godkjennes gjennom hele prosjektets levetid.": "ISO 19650 is about making sure the right information is available to the right people at the right time. The standard sets the framework for how documents and models are organised, named, shared and approved throughout the life of the project.",
 "Kjernen i standarden er et": "At the core of the standard is a",
 ", ett felles sted der all prosjektinformasjon lever, med tydelige statusområder som viser hvor hvert dokument befinner seg i prosessen.": ", one shared place where all project information lives, with clear status areas that show where each document is in the process.",
 "Statusområder": "Status areas",
 "CDE i Dalux": "CDE in Dalux",
 "Slik mapper ISO 19650 statusområdene til Dalux Box sine filområder": "How the ISO 19650 status areas map to the file areas in Dalux Box",
 "Arbeid under utvikling": "Work in progress",
 "→ Filer i Dalux": "→ Files in Dalux",
 "Arbeid pågår. Innhold er under utvikling og ikke klart for deling. Kun synlig for de som har tilgang til mappen.": "Work in progress. Content is being developed and is not ready to share. Only visible to those with access to the folder.",
 "Utkast": "Draft",
 "Under arbeid": "Ongoing",
 "Internt": "Internal",
 "Deling og koordinering": "Sharing and coordination",
 "→ Delte filer i Dalux": "→ Shared files in Dalux",
 "Delt med prosjektteamet for koordinering og tverrfaglig kontroll. Dokumentet er tilgjengelig for kommentering og gjennomgang, men ikke offisielt godkjent.": "Shared with the project team for coordination and cross-discipline checks. The document is available for comments and review, but not officially approved.",
 "Til koordinering": "For coordination",
 "Tverrfaglig": "Cross-discipline",
 "Gjennomgang": "Review",
 "Godkjenning og publisering": "Approval and publishing",
 "→ Utgitte filer i Dalux": "→ Published files in Dalux",
 "Godkjent informasjon. Dokumentet er kontrollert, godkjent og utgitt som gjeldende versjon for alle relevante parter.": "Approved information. The document has been checked, approved and published as the current version for all relevant parties.",
 "Godkjent": "Approved",
 "Gjeldende": "Current",
 "Offisiell": "Official",
 "Arkivering": "Archiving",
 "Utenfor Box": "Outside Box",
 "Arkivering og overlevering kan også håndteres utenfor Box-modulen.": "Archiving and handover can also be handled outside the Box module.",
 ", som er en del av Build-plattformen, håndterer strukturert overlevering til drift. For forvaltning og vedlikehold tilbyr Dalux en egen": ", part of the Build platform, handles structured handover to operations. For facility management and maintenance, Dalux offers a separate",
 "FM-plattform": "FM platform",
 "Overlevering": "Handover",
 "Hvorfor CDE?": "Why a CDE?",
 "Hele poenget med et Common Data Environment er å ha én felles kilde til sannhet. Alle parter vet hvor de finner gjeldende informasjon, og alle dokumenter har en tydelig status som viser hvor langt de har kommet i prosessen.": "The whole point of a Common Data Environment is to have one shared source of truth. Everyone knows where to find the current information, and every document has a clear status that shows how far it has come in the process.",
 "ISO 19650 gir rammeverket, men i praksis må det tilpasses hvert prosjekt. Det er her Dalux Box kommer inn.": "ISO 19650 provides the framework, but in practice it has to be adapted to each project. That is where Dalux Box comes in.",
 "ISO-krav": "ISO requirements",
 "Vis i Dalux": "Show in Dalux",
 "ISO 19650 i": "ISO 19650 in",
 "Statusområder (S0-S3)": "Status areas (S0-S3)",
 "Filområder": "File areas",
 "Tre filområder (Filer, Delte filer og Utgitte filer) mapper direkte til ISO 19650 sine statusområder S0, S1-S2 og S3.": "Three file areas (Files, Shared files and Published files) map directly to the ISO 19650 status areas S0, S1-S2 and S3.",
 "Egnethetskoder (Suitability)": "Suitability codes",
 "Opprett statuser som \"Til koordinering\", \"Til bygging\" eller \"Til godkjenning\" for å merke dokumenters bruksområde.": "Create statuses such as \"For coordination\", \"For construction\" or \"For approval\" to mark what documents may be used for.",
 "Navnekonvensjon": "Naming convention",
 "Navnekonvensjon og regler": "Naming convention and rules",
 "Definer og håndhev en avtalt navnekonvensjon. Standarden krever konsistens, men overlater feltstrukturen til prosjektet.": "Define and enforce an agreed naming convention. The standard requires consistency, but leaves the field structure to the project.",
 "Informasjonsmetadata": "Information metadata",
 "Metadata-felter": "Metadata fields",
 "Legg til egendefinerte felter som fagkode, byggkode, etasjekode og tegningstype for enkel filtrering og søk på tvers av prosjektet.": "Add custom fields such as trade code, building code, floor code and drawing type for easy filtering and search across the project.",
 "Tilgangskontroll": "Access control",
 "Tilgangsstyring per område": "Access control per area",
 "Styr hvem som kan se, laste opp og redigere i hvert filområde. Riktig informasjon til riktige parter.": "Control who can view, upload and edit in each file area. The right information for the right parties.",
 "Informasjonsleveranse (TIDP/MIDP)": "Information delivery (TIDP/MIDP)",
 "Innsendinger": "Submittals",
 "Planlegg og spor filleveranser med ansvarlige, frister, gjennomgangsflyt og godkjenning.": "Plan and track file deliveries with responsible parties, deadlines, review flow and approval.",
 "Godkjenningsflyt": "Approval flow",
 "Gjennomgang og godkjenning": "Review and approval",
 "Formalisert flyt for gjennomgang og godkjenning med definerte roller og sporbare beslutninger.": "A formal review and approval flow with defined roles and traceable decisions.",
 "Sporbarhet (Audit trail)": "Audit trail",
 "Versjonshistorikk og sammenligning": "Version history and comparison",
 "Alle filversjoner arkiveres automatisk. Sammenlign versjoner side om side for å se hva som har endret seg.": "Every file version is archived automatically. Compare versions side by side to see what has changed.",
 "ISO 19650 stiller disse kravene til informasjonshåndtering": "ISO 19650 sets these requirements for information management",
 "Dalux Box Pro er bygget for å støtte ISO 19650 i praksis": "Dalux Box Pro is built to support ISO 19650 in practice",
 "For å oppfylle ISO 19650 må en rekke krav til informasjonshåndtering være på plass. Dalux Box Pro dekker disse kravene med konkrete funksjoner som kan konfigureres og tilpasses hvert prosjekt.": "To meet ISO 19650, a number of information management requirements must be in place. Dalux Box Pro covers them with concrete features that can be configured and adapted to each project.",
 "Under ser du kravene fra standarden. Trykk": "Below are the requirements of the standard. Press",
 "for å se hvilke funksjoner i Box som dekker hvert krav.": "to see which Box features cover each requirement.",
 "Slik dekker Dalux Box Pro hvert ISO 19650-krav": "How Dalux Box Pro covers each ISO 19650 requirement",
 "Dalux Box i praksis": "Dalux Box in practice",
 "Ikke alle prosjekter trenger full ISO 19650. Tilpass bruken av Dalux Box til prosjektets behov.": "Not every project needs full ISO 19650. Adapt how you use Dalux Box to the project’s needs.",
 "Nivå 1": "Level 1",
 "Enkel dokumenthåndtering": "Simple document management",
 "Bruk Box som ren fillagring med oversiktlig mappestruktur. Egner seg for prosjekter som trenger orden uten formell prosess.": "Use Box as plain file storage with a clear folder structure. Suits projects that need order without a formal process.",
 "Mappestruktur per fag/disiplin": "Folder structure per trade/discipline",
 "Automatisk versjonering ved opplasting": "Automatic versioning on upload",
 "Aktivering av Microsoft 365": "Microsoft 365 enabled",
 "Tilgangsstyring per mappe": "Access control per folder",
 "Nivå 2": "Level 2",
 "Strukturert med sporbarhet": "Structured and traceable",
 "Innfør filområder, metadata og navnekonvensjoner for bedre sporbarhet og struktur. Du kan filtrere og søke i dokumenter på tvers av prosjektet.": "Introduce file areas, metadata and naming conventions for better traceability and structure. You can filter and search documents across the project.",
 "Mapper = statusområder (Filer → Utgitte filer)": "Folders = status areas (Files → Published files)",
 "Tilgangsstyring per statusområde": "Access control per status area",
 "Navnekonvensjon for filer": "Naming convention for files",
 "Metadata-felter (status, revisjon, fag)": "Metadata fields (status, revision, trade)",
 "Automatiske hyperlinker mellom tegninger basert på navnekonvensjon": "Automatic hyperlinks between drawings based on the naming convention",
 "Egendefinerte statuser for dokumenter": "Custom statuses for documents",
 "Sammenligning av tegninger, modeller og dokumenter mot tidligere versjoner": "Comparison of drawings, models and documents with earlier versions",
 "Nivå 3": "Level 3",
 "ISO 19650-tilpasset CDE": "ISO 19650-aligned CDE",
 "Komplett oppsett med alle tre filområder, formalisert leveranse- og godkjenningsflyt, og full sporbarhet i tråd med ISO 19650.": "A complete setup with all three file areas, a formal delivery and approval flow, and full traceability in line with ISO 19650.",
 "Tre filområder (Filer → Delte filer → Utgitte filer)": "Three file areas (Files → Shared files → Published files)",
 "Innsendinger med planlagte leveranser, frister og ansvarlige": "Submittals with planned deliveries, deadlines and responsible parties",
 "Formalisert gjennomgangs- og godkjenningsflyt": "Formal review and approval flow",
 "Avtalt navnekonvensjon for hele prosjektet": "An agreed naming convention for the whole project",
 "Slik flyter et dokument gjennom CDE": "How a document flows through the CDE",
 "Følg et dokument fra utkast til godkjent versjon": "Follow a document from draft to approved version",
 "Filer": "Files",
 "Delte filer": "Shared files",
 "Utgitte filer": "Published files",
 "Prosjekterende laster opp utkast": "Designer uploads a draft",
 "Arkitekt laster opp første versjon av plantegning 2. etasje i Filer-området. Dokumentet er kun synlig for arkitektens team og er under utvikling.": "The architect uploads the first version of the level 2 floor plan to the Files area. The document is only visible to the architect’s team and is still being developed.",
 "Filer (under arbeid)": "Files (in progress)",
 "Intern kontroll og oppdatering": "Internal check and update",
 "Fagansvarlig gjennomgår tegningen internt og legger inn kommentarer. Arkitekt oppdaterer og laster opp ny revisjon. Dokumentet er fortsatt i Filer.": "The discipline lead reviews the drawing internally and adds comments. The architect updates it and uploads a new revision. The document is still in Files.",
 "Under revisjon": "Under revision",
 "Delt for tverrfaglig koordinering": "Shared for cross-discipline coordination",
 "Dokumentet flyttes til Delte filer og blir tilgjengelig for alle prosjekterende. RiB og RiV kan nå se tegningen og koordinere sine fag mot den.": "The document is moved to Shared files and becomes available to all designers. STR and HVAC can now see the drawing and coordinate their disciplines against it.",
 "Delt for koordinering": "Shared for coordination",
 "Kommentarer og tilbakemelding": "Comments and feedback",
 "RiB melder om kollisjon med bæresystem. Dokumentet sendes tilbake til Filer for oppdatering. Etter revidering deles ny versjon på nytt i Delte filer.": "STR reports a clash with the load-bearing structure. The document is sent back to Files to be updated. After revision, the new version is shared again in Shared files.",
 "Revidert etter kommentarer": "Revised after comments",
 "Godkjent og publisert": "Approved and published",
 "Etter gjennomgang er dokumentet godkjent og flyttes til Utgitte filer. Dette er nå gjeldende versjon som entreprenører og byggherren forholder seg til.": "After review the document is approved and moved to Published files. This is now the current version that contractors and the client work from.",
 "Godkjent · Gjeldende": "Approved · Current",
 "Alle revisjoner, kommentarer og statusendringer er logget. Historikken viser hele løpet fra første utkast til godkjent versjon. Videre arkivering (ISO S4) håndteres utenfor Box, f.eks. gjennom Dalux Handover for overlevering til drift, eller Dalux FM for forvaltning og vedlikehold.": "Every revision, comment and status change is logged. The history shows the whole path from first draft to approved version. Further archiving (ISO S4) is handled outside Box, for example in Dalux Handover for handover to operations, or Dalux FM for facility management and maintenance.",
 "Dokumentert ✓": "Documented ✓",
 "← Forside": "← Home",
 "Hva er en brukergruppe?": "What is a user group?",
 "Standardgruppene": "The default groups",
 "Slik bygger du gode grupper": "How to build good groups",
 "Grunnstrukturen for rettigheter, samarbeid og sporbarhet i Dalux": "The basic structure for rights, collaboration and traceability in Dalux",
 "Brukergrupper styrer hvem som kan hva i Dalux": "User groups decide who can do what in Dalux",
 "Du gir ikke rettigheter til personer direkte. Du lager grupper, gir gruppene rettigheter, og legger personene inn der de hører hjemme. En person kan være med i flere grupper, og får dermed ulike roller og rettigheter avhengig av modul og arbeidsforløp.": "You don’t give rights to people directly. You create groups, give the groups rights, and put people where they belong. A person can be in several groups, and so gets different roles and rights depending on the module and workflow.",
 "Et byggeprosjekt har mange personer. Hver med sin rolle og sitt firma.": "A construction project has many people, each with their own role and company.",
 "Vi samler personene i grupper. Da slipper vi å styre hver person for seg, og noen kan være med i flere grupper.": "We gather the people into groups. Then we don’t have to manage each person separately, and some people can be in several groups.",
 "Klikk på en person for å se hvilke moduler de får tilgang til via sine grupper.": "Click a person to see which modules they get access to through their groups.",
 "Standardgruppene i Dalux": "The default groups in Dalux",
 "Gruppene som finnes når du oppretter et nytt prosjekt": "The groups that exist when you create a new project",
 "Generelt": "General",
 "Generell admin": "General admin",
 "Prosjektadministratorer": "Project administrators",
 "Har full tilgang til alle prosjektets innstillinger og kan opprette brukergrupper, sette rettigheter og invitere brukere. De ser innholdet i Box, men har i utgangspunktet ingen lese- eller oppretter-rettigheter i Field, noe de kan gi seg selv siden de styrer rettighetene.": "Has full access to all project settings and can create user groups, set rights and invite users. They see the content in Box, but by default have no read or create rights in Field, which they can give themselves since they control the rights.",
 "Field-administratorer": "Field administrators",
 "Administrerer Field-modulen. Setter opp arbeidspakker, arbeidsforløp og maler for oppgaver, sjekklister, testplaner osv. Kan flytte personer mellom Field-grupper, men kan ikke invitere nye til prosjektet.": "Manages the Field module. Sets up work packages, workflows and templates for tasks, checklists, test plans and so on. Can move people between Field groups, but cannot invite new people to the project.",
 "⚠ Viktig!": "⚠ Important!",
 "Auto-rolle i alle workflows": "Auto-role in all workflows",
 "Oppgave- og sjekklistekoordinator": "Task and checklist coordinator",
 "Du plasseres automatisk som oppretter i ALLE arbeidsforløp på prosjektet. Det overstyrer andre svarer-roller du måtte ha. Anbefales kun for de som faktisk skal koordinere alt. Har du andre roller i prosjektet, ikke vær med her.": "You are automatically placed as creator in ALL workflows on the project. This overrides any responder roles you have. Only recommended for people who will actually coordinate everything. If you have other roles in the project, don’t join this group.",
 "Lesetilgang": "Read access",
 "Field-observatører": "Field observers",
 "Kan se det meste i Field, men ikke møter og mengder (med mindre de får egen tilgang via en egendefinert gruppe). Kan ikke se kladder eller motta varsler ved endringer.": "Can see most things in Field, but not meetings and quantities (unless they get separate access through a custom group). Cannot see drafts or receive notifications about changes.",
 "HMS-ansvarlig": "Safety lead",
 "Ansvarlig for HMS-funksjonene. Får automatisk HMS-arbeidsforløp i alle arbeidspakker der HMS er aktivert. Mottar alle HMS-observasjoner. Kan ikke redigere HMS-malene selv.": "Responsible for the safety features. Automatically gets the safety workflow in every work package where Safety is enabled. Receives all safety observations. Cannot edit the safety templates.",
 "Box og Lokasjoner": "Box and Locations",
 "Administrerer Box og Lokasjoner. Oppretter og styrer lokasjoner, bygninger og mappestruktur. Lager versjonsett, distribusjonslister, review packages og kommentarer. Kan håndtere filområder og fil-flyt, inkludert tvungen publisering og godkjenning.": "Manages Box and Locations. Creates and manages locations, buildings and the folder structure. Creates version sets, distribution lists, review packages and comments. Can manage file areas and file flows, including forced publishing and approval.",
 "Innsendingsansvarlig": "Submittals manager",
 "Tilgjengelig kun når innsendingsfunksjonen er aktivert i prosjektet. Har tilgang til alle innsendingsinnstillinger og administrerer prosjektets innsendinger og leveranser.": "Only available when Submittals is enabled in the project. Has access to all submittal settings and manages the project’s submittals and deliveries.",
 "Hvorfor flere små grupper gir bedre kontroll enn én stor": "Why several small groups give better control than one big one",
 "Det er fristende å lage få og store brukergrupper for å holde det enkelt. Men det gjør det vanskelig å gi presise rettigheter og målrette informasjon. Flere små grupper gir mer kontroll over hva folk kan opprette, redigere og se i hver modul.": "It is tempting to create a few large user groups to keep things simple. But that makes it hard to give precise rights and target information. Several small groups give more control over what people can create, edit and see in each module.",
 "Nummereringssystem": "Numbering system",
 "Hver gruppe starter med et nummer. Det gir samme rekkefølge på alle prosjekter siden Dalux sorterer alfabetisk på gruppenavn.": "Each group starts with a number. That gives the same order in every project, since Dalux sorts group names alphabetically.",
 "Én gruppe per firma/kontrakt": "One group per company/contract",
 "Brukerne i én gruppe bør komme fra samme firma eller kontrakt. Da kan du enkelt målrette alle fra samme aktør i arbeidsforløp.": "The users in a group should come from the same company or contract. Then you can easily target everyone from the same party in workflows.",
 "Splitt per fag når relevant": "Split by trade when relevant",
 "Hvis ett firma dekker flere fag, lag undergrupper med samme rot-nummer (40, 41, 42 osv.). Du kan da gi ulike rettigheter til hvert fag.": "If one company covers several trades, create subgroups with the same root number (40, 41, 42 and so on). You can then give each trade different rights.",
 "Eksempel: Brukergrupper i et byggeprosjekt": "Example: User groups in a construction project",
 "Byggeledelse": "Site management",
 "Lars Anlegg AS (totalentreprenør)": "Lars Anlegg AS (main contractor)",
 "Betongmiljø AS (RiB)": "Betongmiljø AS (STR)",
 "Betongmiljø AS - Konstruksjon": "Betongmiljø AS - Structural",
 "Betongmiljø AS - Geoteknikk": "Betongmiljø AS - Geotechnical",
 "Fasade & Form AS (ARK)": "Fasade & Form AS (ARC)",
 "Strøm & Lys AS (RiE)": "Strøm & Lys AS (ELE)",
 "Klima AS (RiV)": "Klima AS (HVAC)",
 "HMS-koordinator": "Safety coordinator",
 "Hva får du med å splitte?": "What do you gain by splitting?",
 "Se forskjellen mellom én bred gruppe og fagsplittede grupper": "See the difference between one broad group and groups split by trade",
 "Mindre fleksibelt": "Less flexible",
 "40 - Betongmiljø AS (én stor)": "40 - Betongmiljø AS (one big group)",
 "Alle fagene i Betongmiljø får samme rettigheter. Geoteknikere får tilgang til konstruksjonsmodeller selv om de ikke trenger det. Varsler om konstruksjons-revisjoner går til geoteknikere som heller ikke trenger dem.": "Every trade in Betongmiljø gets the same rights. Geotechnical engineers get access to structural models even though they don’t need them. Notifications about structural revisions go to geotechnical engineers who don’t need them either.",
 "Mer presis": "More precise",
 "41 + 42 (fagsplittet)": "41 + 42 (split by trade)",
 "Konstruksjon (41) og Geoteknikk (42) får ulike rettigheter og varsler. Du kan målrette en kommentar til kun riktig fag, og hver gruppe ser bare det som er relevant for dem. Begge er fortsatt under \"40 Betongmiljø\" for sortering.": "Structural (41) and Geotechnical (42) get different rights and notifications. You can target a comment to the right trade only, and each group sees only what is relevant to them. Both still sit under \"40 Betongmiljø\" for sorting.",
 "Totalentr.": "Main contr.",
 "TE-fagleder": "MC trade lead",
 "Opprette oppgaver": "Create tasks",
 "Utføre kontrollplaner": "Carry out inspection plans",
 "Utføre sjekklister": "Carry out checklists",
 "Skrive kommentar": "Write comments",
 "Lukke kommentar": "Close comments",
 "Laste opp filer": "Upload files",
 "Godkjenne filer": "Approve files",
 "I Field": "In Field",
 "er medlem av": "is a member of",
 "og kan utføre": "and can do",
 "i Field og Box.": "in Field and Box.",
 "Forrige side": "Previous page",
 "Neste side": "Next page",
 "Sider i dette temaet": "Pages in this topic",
 "Deler av Samhandling i Box": "Parts of Collaboration in Box",
 "Velg scenario": "Choose a scenario"
};

/* Mønstre for tekst som bygges med tall eller navn (norsk regex, engelsk mal, engelsk regex, norsk mal) */
const I18N_RULES = [["^(\\d+) gruppe$", "\\1 group", "^(\\d+) group$", "\\1 gruppe"], ["^(\\d+) grupper$", "\\1 groups", "^(\\d+) groups$", "\\1 grupper"], ["^(\\d+) handling$", "\\1 action", "^(\\d+) action$", "\\1 handling"], ["^(\\d+) handlinger$", "\\1 actions", "^(\\d+) actions$", "\\1 handlinger"], ["^(.+) \\+ (\\d+) mer$", "\\1 + \\2 more", "^(.+) \\+ (\\d+) more$", "\\1 + \\2 mer"]];
